from __future__ import annotations

__all__ = ["_tavily_search", "_iso_to_date", "_safe_slug", "_gemini_generate_image_bytes"]

from typing import List, Dict, Any
from datetime import date
import re
from langchain_community.tools.tavily_search import TavilySearchResults
import os

def _tavily_search(query: str, max_results: int = 5) -> List[Dict[str, Any]]:
    """
    Uses TavilySearchResults if installed and TAVILY_API_KEY is set.
    Returns list of dict with common fields. Note: published date is often missing.
    """
    tool = TavilySearchResults(max_results=max_results)
    results = tool.invoke({"query": query})

    normalized: List[dict] = []

    for r in results or []:
        normalized.append(
            {
                "title": r.get("title") or "",
                "url": r.get("url") or "",
                "snippet": r.get("content") or r.get("snippet") or "",
                "published_at": r.get("published_date") or r.get("published_at"),
                "source": r.get("source"),
            }
        )
    
    return normalized


def _iso_to_date(s: str|None) -> date|None:
    if not s:
        return None
    try:
        return date.fromisoformat(s[:10])
    except Exception:
        return None
    
def _safe_slug(title: str) -> str:
    s = title.strip().lower()
    s = re.sub(r"[^a-z0-9 _-]+", "", s)
    s = re.sub(r"\s+", "_", s).strip("_")
    return s or "blog"
    

def _gemini_generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw PNG image bytes generated by Imagen 4 via the google-genai SDK.
    Requires: pip install google-genai
    Env var: GOOGLE_API_KEY
    """
    from google import genai
    from google.genai import types

    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        raise RuntimeError("GOOGLE_API_KEY is not set.")

    client = genai.Client(api_key=api_key)

    resp = client.models.generate_images(
        model="imagen-4.0-generate-001",
        prompt=prompt,
        config=types.GenerateImagesConfig(
            number_of_images=1,
            output_mime_type="image/png",
        ),
    )

    generated = getattr(resp, "generated_images", None)
    if not generated:
        raise RuntimeError("No images returned (safety filter or quota).")

    image_bytes = generated[0].image.image_bytes
    if not image_bytes:
        raise RuntimeError("Image bytes are empty.")

    return image_bytes